# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GenericsAndProtocolApi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

	pod 'Alamofire'

  # Pods for GenericsAndProtocolApi

  target 'GenericsAndProtocolApiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GenericsAndProtocolApiUITests' do
    # Pods for testing
  end

end
